CC:=g++

SOURCEDIR:=source
HEADERDIR:=header
OBJECTDIR:=object
DEPENDDIR:=dep
BINARYDIR:=bin

SOURCES:=$(shell find $(SOURCEDIR) -name '*.cc')
OBJECTS:=$(subst $(SOURCEDIR),$(OBJECTDIR), $(subst .cc,.o, $(SOURCES)))
DEPENDS:=$(subst $(SOURCEDIR),$(DEPENDDIR), $(subst .cc,.d, $(SOURCES)))

FLAGS:=-Wall -Wextra -pedantic -std=c++14 -I./$(HEADERDIR)

name:=main

